name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: |
          cd client
          npm install
          cd ../server
          npm install
      - name: Build client
        run: |
          cd client
          npm run build
      - name: Deploy to Render
        uses: renderinc/render-deploy-action@v1.3.3
        with:
          renderEmail: ${{ secrets.RENDER_EMAIL }}
          renderPassword: ${{ secrets.RENDER_PASSWORD }}
          buildCommand: ''
          startCommand: 'npm start'
          port: 3000